export { authRepo } from './auth'
export { productRepo } from './products'
export { orderRepo } from './orders'
export { technicianRepo } from './technicians'
export { customerRepo } from './customers'
export { memberRepo } from './members'
export { notificationRepo } from './notifications'
export { reportRepo } from './reports'
export { inventoryRepo } from './inventory'
export { promotionRepo } from './promotions'
export { documentRepo } from './documents'
export { modelRepo } from './models'
export { reservationRepo } from './reservations'
export { scheduleRepo } from './schedule'
export { staffRepo } from './staff'
export { settingsRepo } from './settings'
export { payrollRepo } from './payroll'
export { usedItemRepo } from './used_items'
export { productMetaRepo } from './product_meta'


